" press 'K' in vim to get help for the used options
source $VIMRUNTIME/defaults.vim
set termguicolors
set title
set formatoptions+=j
set hidden
colorscheme eldar

function TabToggle()
  if &expandtab
    set shiftwidth=8
    set softtabstop=0
    set noexpandtab
  else
    set shiftwidth=4
    set softtabstop=4
    set expandtab
  endif
endfunction
