" press 'K' in vim to get help for the used options
source $VIMRUNTIME/defaults.vim
if !has("gui_running")
	set background=dark
endif
set termguicolors
set title
set formatoptions+=j
set hidden
"set hlsearch
"set expandtab
"set tabstop=4
"set shiftwidth=4
